-- ==========================================
-- SERENECHECK DATABASE INITIALIZATION SCRIPT
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 0. Drop existing empty tables to ensure clean recreation with proper unique constraints
DROP TABLE IF EXISTS public.rules CASCADE;
DROP TABLE IF EXISTS public.gejala CASCADE;
DROP TABLE IF EXISTS public.gangguan CASCADE;
DROP TABLE IF EXISTS public.diagnosis CASCADE;

-- 1. Create gangguan table
CREATE TABLE public.gangguan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_gangguan VARCHAR(50) UNIQUE NOT NULL,
    nama VARCHAR(255) NOT NULL,
    deskripsi TEXT NOT NULL,
    solusi TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 2. Create gejala table
CREATE TABLE public.gejala (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_gejala VARCHAR(50) UNIQUE NOT NULL,
    nama_gejala TEXT NOT NULL,
    deskripsi TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 3. Create rules table
CREATE TABLE public.rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gangguan_id BIGINT NOT NULL REFERENCES public.gangguan(id) ON DELETE CASCADE,
    gejala_id BIGINT NOT NULL REFERENCES public.gejala(id) ON DELETE CASCADE,
    cf_pakar NUMERIC NOT NULL,
    CONSTRAINT unique_rule UNIQUE (gangguan_id, gejala_id)
);

-- 4. Create diagnosis table
CREATE TABLE public.diagnosis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hasil VARCHAR(255) NOT NULL,
    nilai_cf NUMERIC NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 5. Disable Row Level Security (RLS) to allow simple public queries
ALTER TABLE public.gangguan DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.gejala DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnosis DISABLE ROW LEVEL SECURITY;

-- 6. Insert Gangguan Data
INSERT INTO public.gangguan (kode_gangguan, nama, deskripsi, solusi) VALUES
('S1', 'Stress Ringan', 'Tingkat stres ringan yang biasanya disebabkan oleh rutinitas harian, tenggat waktu tugas, atau ketegangan sementara. Ini wajar terjadi dan tidak mengganggu fungsi sehari-hari secara signifikan.', 'Lakukan manajemen waktu yang baik, luangkan waktu untuk relaksasi atau hobi, olahraga teratur, tidur cukup, serta bicarakan keluh kesah dengan teman dekat.'),
('S2', 'Stress Sedang', 'Tingkat stres sedang di mana tekanan mulai menumpuk, menyebabkan keletihan fisik dan emosional. Stres ini mulai memengaruhi produktivitas kuliah dan fokus pengerjaan skripsi.', 'Buat jadwal pengerjaan skripsi yang realistis (pecah menjadi tugas-tugas kecil), komunikasikan kendala dengan dosen pembimbing, batasi konsumsi kafein, praktikkan teknik pernapasan atau meditasi secara berkala, dan luangkan waktu untuk beristirahat tanpa layar gadget.'),
('S3', 'Stress Berat', 'Tingkat stres berat yang ditandai dengan kecemasan tinggi, keputusasaan, insomnia parah, atau penarikan diri secara sosial. Kondisi ini mengganggu aktivitas sehari-hari secara mendalam dan memerlukan perhatian khusus.', 'Sangat dianjurkan untuk berkonsultasi dengan profesional kesehatan mental (psikolog atau psikiater). Lakukan jeda akademis jika diperlukan, ikuti konseling mahasiswa, terapkan self-care yang ketat, dan carilah support system terdekat untuk membantu Anda melewati fase ini.')
ON CONFLICT (kode_gangguan) DO UPDATE 
SET nama = EXCLUDED.nama, deskripsi = EXCLUDED.deskripsi, solusi = EXCLUDED.solusi;

-- 7. Insert Gejala Data
INSERT INTO public.gejala (kode_gejala, nama_gejala, deskripsi) VALUES
('G01', 'Kesulitan tidur (insomnia) atau tidur berlebihan', 'Mengalami gangguan tidur seperti sulit memejamkan mata atau tidur terlalu lama.'),
('G02', 'Merasa lelah sepanjang waktu meskipun sudah beristirahat', 'Keletihan fisik kronis meskipun tidak melakukan aktivitas fisik berat.'),
('G03', 'Sering mengalami sakit kepala atau pusing secara tiba-tiba', 'Sakit kepala tegang yang sering muncul di sekitar dahi atau belakang kepala.'),
('G04', 'Ketegangan otot di bahu, leher, atau punggung', 'Otot terasa kaku dan pegal akibat kecemasan atau postur duduk yang buruk.'),
('G05', 'Perubahan nafsu makan secara drastis', 'Nafsu makan menurun tajam atau makan berlebihan secara emosional (emotional eating).'),
('G06', 'Kesulitan berkonsentrasi atau fokus saat mengerjakan skripsi', 'Pikiran mudah teralihkan dan sulit memahami materi bimbingan atau referensi.'),
('G07', 'Sering menunda-nunda pengerjaan tugas atau bimbingan skripsi', 'Kecenderungan untuk menunda tugas akademik (prokrastinasi) karena rasa takut.'),
('G08', 'Merasa cemas, khawatir berlebih, atau panik', 'Kecemasan intens terhadap masa depan, kelulusan, atau saat berhadapan dengan dosen.'),
('G09', 'Menjadi lebih mudah marah, tersinggung, atau sensitif terhadap kritik', 'Emosi tidak stabil ketika mendapat masukan revisi atau saat berdiskusi.'),
('G10', 'Merasa sedih, murung, atau kehilangan minat pada aktivitas yang disukai', 'Mood yang menurun terus menerus (depresi ringan) dan tidak bersemangat.'),
('G11', 'Merasa terbebani secara berlebihan oleh ekspektasi dosen atau orang tua', 'Tekanan psikologis karena ingin memenuhi harapan orang lain.'),
('G12', 'Menarik diri dari interaksi sosial dengan teman atau keluarga', 'Memilih menyendiri dan menghindari obrolan mengenai perkuliahan atau masa depan.'),
('G13', 'Mengalami jantung berdebar kencang saat memikirkan revisi atau sidang', 'Reaksi kecemasan fisik berupa takikardia ringan.'),
('G14', 'Merasa ragu dengan kemampuan diri sendiri dan takut gagal menyelesaikan kuliah', 'Krisis kepercayaan diri (imposter syndrome) terkait penyelesaian skripsi.'),
('G15', 'Sering merasa gelisah, tidak tenang, atau tidak bisa rileks', 'Kondisi tidak tenang secara konstan meskipun sedang tidak mengerjakan tugas.')
ON CONFLICT (kode_gejala) DO UPDATE 
SET nama_gejala = EXCLUDED.nama_gejala, deskripsi = EXCLUDED.deskripsi;

-- 8. Insert Rules Data
INSERT INTO public.rules (gangguan_id, gejala_id, cf_pakar) VALUES
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S1'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G01'), 0.40),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S1'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G02'), 0.30),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S1'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G03'), 0.30),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S1'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G05'), 0.40),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S1'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G07'), 0.50),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S1'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G09'), 0.40),

((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G01'), 0.60),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G02'), 0.50),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G06'), 0.70),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G07'), 0.60),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G08'), 0.60),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G09'), 0.60),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G11'), 0.70),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G14'), 0.60),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S2'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G15'), 0.50),

((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G01'), 0.80),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G03'), 0.70),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G04'), 0.80),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G06'), 0.80),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G08'), 0.80),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G10'), 0.90),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G12'), 0.80),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G13'), 0.80),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G14'), 0.90),
((SELECT id FROM public.gangguan WHERE kode_gangguan = 'S3'), (SELECT id FROM public.gejala WHERE kode_gejala = 'G15'), 0.80)
ON CONFLICT (gangguan_id, gejala_id) DO UPDATE 
SET cf_pakar = EXCLUDED.cf_pakar;
